name: Update some list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Execute every week at 0:00 CST (UTC+8), which is 16:00 UTC on the previous day
    - cron: '0 1 * * *' # Runs at 01:00 UTC every day, which is 09:00 Beijing time
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: some generator
        uses: simonecorsi/mawesome@v2.2.0
        with:
          api-token: ${{ secrets.PERSONAL_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          template-path: "template/README.ejs"
          github-name: ${{ github.repository_owner }}
